services:
  a-service:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - common
    restart: unless-stopped
    command: node dist/a-service.js

  b-service:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - common
    restart: unless-stopped
    command: node dist/b-service.js


  nginx:
    user: root
    image: nginx:latest
    networks:
      - common
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:rw
      - ./index.html:/app/index.html
    restart: unless-stopped
    ports:
      - 0.0.0.0:5555:80



networks:
  common:
    driver: bridge
